# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_key', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=255)),
                ('subscription_notify', models.CharField(blank=True, max_length=255)),
                ('unsubscription_notify', models.CharField(blank=True, max_length=255)),
                ('to_name', models.CharField(blank=True, max_length=255)),
                ('carboncopy', models.CharField(blank=True, max_length=255)),
                ('sender_remember', models.TextField(blank=True, null=True)),
                ('sender_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
            },
        ),
    ]
