# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activecampaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='carboncopy',
        ),
        migrations.RemoveField(
            model_name='list',
            name='to_name',
        ),
    ]
