# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activecampaign', '0002_auto_20180116_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_key', models.IntegerField(blank=True, default=0, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('list_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activecampaign.List')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
