# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activecampaign', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_key', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sdate', models.DateTimeField()),
                ('list_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activecampaign.List')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activecampaign.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
